### ISSUE TITLE
v0.0.5

### ISSUE THREAD

**Issue by sachin21** [sachin21/dmm-crawler#27]
# Tasks
- [x] Add a tag for version.
- [x] Release chang logs.
- [ ] Push to `rubygems.org`.
